/*
 * chassis.h
 *
 *  Created on: Nov 6, 2020
 *      Author: xqe2011
 */

#ifndef CHASSIS_H_
#define CHASSIS_H_

/* 任务是否启用设置 */
#define CONFIG_CHASSIS_ENABLE

/* 底盘轮距(mm) */
#define CONFIG_CHASSIS_WHEELTRACK     353
/* 底盘轴距(mm) */
#define CONFIG_CHASSIS_WHEELBASE      370
/* 云台偏移(mm) */
#define CONFIG_CHASSIS_GIMBAL_OFFSET  0
/* 底盘轮子周长(mm) */
#define CONFIG_CHASSIS_PERIMETER      478
/* 底盘电机减速比(3508) */
#define CONFIG_CHASSIS_DECELE_RATIO   (1.0f/19.0f)
/* 单个电机速度极限，单位是分钟每转, 8347rpm = 3500mm/s */
#define CONFIG_CHASSIS_MAX_WHEEL_RPM  8500
/* 底盘移动最大速度，单位是毫米每秒 */
#define CONFIG_CHASSIS_MAX_VX_SPEED   1000
#define CONFIG_CHASSIS_MAX_VY_SPEED   1000
/* 底盘旋转最大速度，单位是度每秒 */
#define CONFIG_CHASSIS_MAX_VR_SPEED   100

/**
 * 电机ID配置,这里的ID并非是电调ID,而是电机信息数组的index
 * LF: 底盘左前方电机
 * RF: 底盘右前方电机
 * LB: 底盘左后方电机
 * RB: 底盘右后方电机
 */
#define CONFIG_CHASSIS_MOTOR_RF 0
#define CONFIG_CHASSIS_MOTOR_LF 1
#define CONFIG_CHASSIS_MOTOR_LB 2
#define CONFIG_CHASSIS_MOTOR_RB 3
#define CONFIG_CHASSIS_MOTOR_GIMBAL_YAW 4

/* PID参数定义 */
/* 四个电机的速度环PID */
#define CONFIG_PID_CHASSIS_RF_P 1
#define CONFIG_PID_CHASSIS_RF_I 1
#define CONFIG_PID_CHASSIS_RF_D 0
#define CONFIG_PID_CHASSIS_RF_MAX_OUTPUT 5000
#define CONFIG_PID_CHASSIS_RF_INTERGRAL_LIMIT 1000
#define CONFIG_PID_CHASSIS_RF_DCT_ENABLE 0

#define CONFIG_PID_CHASSIS_LF_P 1
#define CONFIG_PID_CHASSIS_LF_I 1
#define CONFIG_PID_CHASSIS_LF_D 0
#define CONFIG_PID_CHASSIS_LF_MAX_OUTPUT 5000
#define CONFIG_PID_CHASSIS_LF_INTERGRAL_LIMIT 1000
#define CONFIG_PID_CHASSIS_LF_DCT_ENABLE 0

#define CONFIG_PID_CHASSIS_LB_P 1
#define CONFIG_PID_CHASSIS_LB_I 1
#define CONFIG_PID_CHASSIS_LB_D 0
#define CONFIG_PID_CHASSIS_LB_MAX_OUTPUT 5000
#define CONFIG_PID_CHASSIS_LB_INTERGRAL_LIMIT 1000
#define CONFIG_PID_CHASSIS_LB_DCT_ENABLE 0

#define CONFIG_PID_CHASSIS_RB_P 1
#define CONFIG_PID_CHASSIS_RB_I 1
#define CONFIG_PID_CHASSIS_RB_D 0
#define CONFIG_PID_CHASSIS_RB_MAX_OUTPUT 5000
#define CONFIG_PID_CHASSIS_RB_INTERGRAL_LIMIT 1000
#define CONFIG_PID_CHASSIS_RB_DCT_ENABLE 0

/* 底盘跟随云台环的PID */
#define CONFIG_PID_CHASSIS_FOLLOW_P 0.1
#define CONFIG_PID_CHASSIS_FOLLOW_I 0
#define CONFIG_PID_CHASSIS_FOLLOW_D 1
#define CONFIG_PID_CHASSIS_FOLLOW_MAX_OUTPUT 3000
#define CONFIG_PID_CHASSIS_FOLLOW_INTERGRAL_LIMIT 1000
#define CONFIG_PID_CHASSIS_FOLLOW_DCT_ENABLE 0

#endif /* CHASSIS_H_ */
