/*
 * gimbal.h
 *
 *  Created on: Nov 6, 2020
 *      Author: xqe2011
 */

#ifndef GIMBAL_H_
#define GIMBAL_H_

/* 云台遥控器PITCH限制,单位为度 */
#define CONFIG_GIMBAL_RC_PITCH_MIN_ANGLE -45
#define CONFIG_GIMBAL_RC_PITCH_MAX_ANGLE 45

/* 云台遥控器YAW限制,单位为度 */
#define CONFIG_GIMBAL_RC_YAW_MIN_ANGLE -60
#define CONFIG_GIMBAL_RC_YAW_MAX_ANGLE 60

/* 云台遥控器增量速度,单位为度 */
#define CONFIG_GIMBAL_RC_PITCH_SPEED 1
#define CONFIG_GIMBAL_RC_YAW_SPEED 3

/* 云台一圈ecd值 */
#define CONFIG_GIMBAL_YAW_ECD 8192.0f

/**
 * 电机ID配置,这里的ID并非是电调ID,而是电机信息数组的index
 */
#define CONFIG_GIMBAL_MOTOR_YAW 4
#define CONFIG_GIMBAL_MOTOR_PITCH 5

/* PID参数定义 */
/* 云台电机校准环的PID */
#define CONFIG_PID_GIMBAL_CALIBRATE_YAW_P 20
#define CONFIG_PID_GIMBAL_CALIBRATE_YAW_I 0.01
#define CONFIG_PID_GIMBAL_CALIBRATE_YAW_D 0
#define CONFIG_PID_GIMBAL_CALIBRATE_YAW_MAX_OUTPUT 5000
#define CONFIG_PID_GIMBAL_CALIBRATE_YAW_INTERGRAL_LIMIT 1000

#define CONFIG_PID_GIMBAL_CALIBRATE_PITCH_P 20
#define CONFIG_PID_GIMBAL_CALIBRATE_PITCH_I 1
#define CONFIG_PID_GIMBAL_CALIBRATE_PITCH_D 0
#define CONFIG_PID_GIMBAL_CALIBRATE_PITCH_MAX_OUTPUT 5000
#define CONFIG_PID_GIMBAL_CALIBRATE_PITCH_INTERGRAL_LIMIT 3000

/* 云台电机角度环的PID */
#define CONFIG_PID_GIMBAL_POSITION_YAW_P 20
#define CONFIG_PID_GIMBAL_POSITION_YAW_I 0
#define CONFIG_PID_GIMBAL_POSITION_YAW_D 0
#define CONFIG_PID_GIMBAL_POSITION_YAW_MAX_OUTPUT 3000
#define CONFIG_PID_GIMBAL_POSITION_YAW_INTERGRAL_LIMIT 1000

#define CONFIG_PID_GIMBAL_POSITION_PITCH_P 20
#define CONFIG_PID_GIMBAL_POSITION_PITCH_I 0
#define CONFIG_PID_GIMBAL_POSITION_PITCH_D 0
#define CONFIG_PID_GIMBAL_POSITION_PITCH_MAX_OUTPUT 3000
#define CONFIG_PID_GIMBAL_POSITION_PITCH_INTERGRAL_LIMIT 1000

/* 云台电机角速度环的PID */
#define CONFIG_PID_GIMBAL_SPEED_YAW_P 25
#define CONFIG_PID_GIMBAL_SPEED_YAW_I 0
#define CONFIG_PID_GIMBAL_SPEED_YAW_D 0
#define CONFIG_PID_GIMBAL_SPEED_YAW_MAX_OUTPUT 5000
#define CONFIG_PID_GIMBAL_SPEED_YAW_INTERGRAL_LIMIT 1000

#define CONFIG_PID_GIMBAL_SPEED_PITCH_P 25
#define CONFIG_PID_GIMBAL_SPEED_PITCH_I 0
#define CONFIG_PID_GIMBAL_SPEED_PITCH_D 0
#define CONFIG_PID_GIMBAL_SPEED_PITCH_MAX_OUTPUT 5000
#define CONFIG_PID_GIMBAL_SPEED_PITCH_INTERGRAL_LIMIT 1000

#endif /* GIMBAL_H_ */
